"""phase3a generic morphology data layer
Revision ID: 202607240001
Revises: 202607230002
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="202607240001"; down_revision="202607230002"; branch_labels=None; depends_on=None
J=postgresql.JSONB(astext_type=sa.Text())

def upgrade():
    op.create_table("annotation_source_release", sa.Column("id",sa.Integer,primary_key=True), sa.Column("name",sa.String(200),nullable=False), sa.Column("version",sa.String(100),nullable=False), sa.Column("format",sa.String(80),nullable=False), sa.Column("publisher",sa.Text,nullable=False), sa.Column("official_url",sa.Text), sa.Column("license",sa.Text,nullable=False), sa.Column("license_url",sa.Text), sa.Column("citation",sa.Text), sa.Column("original_filename",sa.Text,nullable=False), sa.Column("stored_raw_path",sa.Text,nullable=False), sa.Column("raw_sha256",sa.String(64),nullable=False,unique=True), sa.Column("byte_size",sa.Integer,nullable=False), sa.Column("line_count",sa.Integer,nullable=False), sa.Column("parser_name",sa.String(120),nullable=False), sa.Column("parser_version",sa.String(40),nullable=False), sa.Column("parser_config_json",J,nullable=False), sa.Column("parser_config_sha256",sa.String(64),nullable=False), sa.Column("metadata_json",J,nullable=False,server_default=sa.text("'{}'::jsonb")), sa.Column("active_from",sa.DateTime,server_default=sa.text("now()"),nullable=False), sa.Column("active_to",sa.DateTime), sa.UniqueConstraint("name","version"))
    op.create_table("annotation_source_record", sa.Column("id",sa.Integer,primary_key=True), sa.Column("annotation_source_release_id",sa.Integer,sa.ForeignKey("annotation_source_release.id"),nullable=False), sa.Column("source_record_number",sa.Integer,nullable=False), sa.Column("source_line_number",sa.Integer,nullable=False), sa.Column("record_type",sa.String(40),nullable=False), sa.Column("raw_record_content",sa.Text,nullable=False), sa.Column("exact_line_ending",sa.String(4),nullable=False), sa.Column("raw_record_sha256",sa.String(64),nullable=False), sa.Column("parsed_payload_json",J), sa.Column("parse_status",sa.String(40),nullable=False), sa.Column("parse_error",sa.Text), sa.Column("metadata_json",J,nullable=False,server_default=sa.text("'{}'::jsonb")), sa.UniqueConstraint("annotation_source_release_id","source_record_number"))
    op.create_index("ix_annotation_record_source_number","annotation_source_record",["annotation_source_release_id","source_record_number"])
    op.create_index("ix_annotation_record_locator","annotation_source_record",[sa.text("((parsed_payload_json->>'locator'))")])
    for t in ["transliteration_profile","morphology_feature_mapping_profile","alignment_configuration"]:
        op.create_table(t, sa.Column("id",sa.Integer,primary_key=True), sa.Column("name",sa.String(120),nullable=False), sa.Column("version",sa.String(40),nullable=False), sa.Column("description",sa.Text,nullable=False), sa.Column("configuration_json",J,nullable=False), sa.Column("configuration_sha256",sa.String(64),nullable=False,unique=True), sa.Column("is_frozen",sa.Boolean,nullable=False,server_default=sa.text("true")), sa.Column("created_at",sa.DateTime,server_default=sa.text("now()"),nullable=False), sa.UniqueConstraint("name","version"))
    op.create_table("morphology_ingestion_run", sa.Column("id",sa.Integer,primary_key=True), sa.Column("annotation_source_release_id",sa.Integer,sa.ForeignKey("annotation_source_release.id"),nullable=False), sa.Column("quran_source_release_id",sa.Integer,sa.ForeignKey("source_release.id"),nullable=False), sa.Column("alignment_configuration_id",sa.Integer,sa.ForeignKey("alignment_configuration.id"),nullable=False), sa.Column("transliteration_profile_id",sa.Integer,sa.ForeignKey("transliteration_profile.id"),nullable=False), sa.Column("feature_mapping_profile_id",sa.Integer,sa.ForeignKey("morphology_feature_mapping_profile.id"),nullable=False), sa.Column("status",sa.String(40),nullable=False), sa.Column("started_at",sa.DateTime,server_default=sa.text("now()"),nullable=False), sa.Column("completed_at",sa.DateTime), sa.Column("source_record_count",sa.Integer,nullable=False,server_default="0"), sa.Column("parsed_analysis_count",sa.Integer,nullable=False,server_default="0"), sa.Column("segment_count",sa.Integer,nullable=False,server_default="0"), sa.Column("alignment_count",sa.Integer,nullable=False,server_default="0"), sa.Column("malformed_count",sa.Integer,nullable=False,server_default="0"), sa.Column("unknown_count",sa.Integer,nullable=False,server_default="0"), sa.Column("ambiguous_count",sa.Integer,nullable=False,server_default="0"), sa.Column("unaligned_count",sa.Integer,nullable=False,server_default="0"), sa.Column("environment_snapshot_json",J,nullable=False), sa.Column("git_commit_hash",sa.String(64)), sa.Column("git_dirty",sa.Boolean), sa.Column("schema_revision",sa.String(40)), sa.Column("source_hashes_json",J,nullable=False), sa.Column("configuration_hashes_json",J,nullable=False), sa.Column("ingestion_hash",sa.String(64)), sa.Column("ingestion_hash_algorithm",sa.String(80),nullable=False,server_default="morphology-ingestion-hash-v1"), sa.Column("error_message",sa.Text), sa.CheckConstraint("status in ('pending','running','completed','failed','cancelled')"))
    op.create_table("morphological_analysis", sa.Column("id",sa.Integer,primary_key=True), sa.Column("ingestion_run_id",sa.Integer,sa.ForeignKey("morphology_ingestion_run.id"),nullable=False), sa.Column("annotation_source_record_id",sa.Integer,sa.ForeignKey("annotation_source_record.id"),nullable=False), sa.Column("variant_index",sa.Integer,nullable=False), sa.Column("external_locator",sa.Text,nullable=False), sa.Column("parsed_locator_json",J), sa.Column("source_surface",sa.Text), sa.Column("source_transliteration",sa.Text), sa.Column("source_pos",sa.Text), sa.Column("source_lemma",sa.Text), sa.Column("source_root",sa.Text), sa.Column("source_features_json",J,nullable=False), sa.Column("standardized_features_json",J,nullable=False), sa.Column("transliteration_json",J,nullable=False), sa.Column("source_native_payload_json",J,nullable=False), sa.Column("analysis_hash",sa.String(64),nullable=False), sa.Column("analysis_hash_algorithm",sa.String(80),nullable=False,server_default="morphology-analysis-hash-v1"))
    op.create_index("ix_morph_analysis_source","morphological_analysis",["ingestion_run_id","annotation_source_record_id"]); op.create_index("ix_morph_analysis_lemma_root_pos","morphological_analysis",["source_lemma","source_root","source_pos"])
    op.create_table("morphological_segment", sa.Column("id",sa.Integer,primary_key=True), sa.Column("morphological_analysis_id",sa.Integer,sa.ForeignKey("morphological_analysis.id"),nullable=False), sa.Column("segment_index",sa.Integer,nullable=False), sa.Column("external_locator",sa.Text,nullable=False), sa.Column("source_surface",sa.Text), sa.Column("source_transliteration",sa.Text), sa.Column("source_pos",sa.Text), sa.Column("source_features_json",J,nullable=False), sa.Column("codepoint_start_in_source_token",sa.Integer), sa.Column("codepoint_end_in_source_token",sa.Integer), sa.Column("segment_hash",sa.String(64),nullable=False), sa.Column("segment_hash_algorithm",sa.String(80),nullable=False,server_default="morphology-segment-hash-v1"), sa.UniqueConstraint("morphological_analysis_id","segment_index"))
    op.create_index("ix_morph_segment_pos","morphological_segment",["source_pos"])
    op.create_table("annotation_alignment", sa.Column("id",sa.Integer,primary_key=True), sa.Column("ingestion_run_id",sa.Integer,sa.ForeignKey("morphology_ingestion_run.id"),nullable=False), sa.Column("morphological_analysis_id",sa.Integer,sa.ForeignKey("morphological_analysis.id"),nullable=False), sa.Column("morphological_segment_id",sa.Integer,sa.ForeignKey("morphological_segment.id")), sa.Column("annotation_source_record_id",sa.Integer,sa.ForeignKey("annotation_source_record.id"),nullable=False), sa.Column("orthographic_token_id",sa.Integer,sa.ForeignKey("orthographic_token.id")), sa.Column("text_unit_id",sa.Integer,sa.ForeignKey("text_unit.id")), sa.Column("surah_number",sa.Integer), sa.Column("ayah_number",sa.Integer), sa.Column("token_position",sa.Integer), sa.Column("external_locator",sa.Text,nullable=False), sa.Column("alignment_type",sa.String(40),nullable=False), sa.Column("alignment_status",sa.String(40),nullable=False), sa.Column("source_surface",sa.Text), sa.Column("authoritative_raw_token",sa.Text), sa.Column("codepoint_start",sa.Integer), sa.Column("codepoint_end",sa.Integer), sa.Column("comparison_representation",sa.Text), sa.Column("normalization_profile",sa.String(120)), sa.Column("normalization_transformations_json",J,nullable=False), sa.Column("candidates_json",J,nullable=False), sa.Column("decision_rule",sa.Text,nullable=False), sa.Column("confidence",sa.Float,nullable=False), sa.Column("reason",sa.Text,nullable=False), sa.Column("algorithm_version",sa.String(80),nullable=False), sa.Column("conflict_dimensions_json",J,nullable=False,server_default=sa.text("'[]'::jsonb")), sa.Column("alignment_hash",sa.String(64),nullable=False), sa.Column("alignment_hash_algorithm",sa.String(80),nullable=False,server_default="morphology-alignment-hash-v1"))
    for name, cols in [("ix_alignment_raw_token_status",["orthographic_token_id","alignment_status"]),("ix_alignment_status_ingestion",["ingestion_run_id","alignment_status"]),("ix_alignment_locator",["ingestion_run_id","external_locator"]),("ix_alignment_conflict",["ingestion_run_id","alignment_status"] )]: op.create_index(name,"annotation_alignment",cols)
    op.create_table("morphology_export_manifest", sa.Column("id",sa.Integer,primary_key=True), sa.Column("ingestion_run_id",sa.Integer,sa.ForeignKey("morphology_ingestion_run.id"),nullable=False), sa.Column("entity",sa.String(40),nullable=False), sa.Column("path",sa.Text,nullable=False), sa.Column("format",sa.String(20),nullable=False), sa.Column("export_file_sha256",sa.String(64),nullable=False), sa.Column("manifest_sha256",sa.String(64),nullable=False,unique=True), sa.Column("canonical_json",J,nullable=False), sa.Column("created_at",sa.DateTime,server_default=sa.text("now()"),nullable=False))
    op.execute('''create or replace function block_phase3a_immutable() returns trigger as $$ begin raise exception '% rows are immutable', TG_TABLE_NAME; end; $$ language plpgsql;
create trigger trg_annotation_source_release_immutable before update or delete on annotation_source_release for each row execute function block_phase3a_immutable();
create trigger trg_annotation_source_record_immutable before update or delete on annotation_source_record for each row execute function block_phase3a_immutable();
create trigger trg_transliteration_profile_frozen before update or delete on transliteration_profile for each row when (OLD.is_frozen) execute function block_phase3a_immutable();
create trigger trg_feature_profile_frozen before update or delete on morphology_feature_mapping_profile for each row when (OLD.is_frozen) execute function block_phase3a_immutable();
create trigger trg_alignment_config_frozen before update or delete on alignment_configuration for each row when (OLD.is_frozen) execute function block_phase3a_immutable();
create or replace function block_completed_morphology_run_update() returns trigger as $$ begin if OLD.status = 'completed' then raise exception 'completed morphology_ingestion_run rows are immutable'; end if; return NEW; end; $$ language plpgsql;
create trigger trg_completed_morphology_run_immutable before update or delete on morphology_ingestion_run for each row execute function block_completed_morphology_run_update();
create or replace function block_completed_morphology_payload_update() returns trigger as $$ begin if exists (select 1 from morphology_ingestion_run r where r.id = OLD.ingestion_run_id and r.status = 'completed') then raise exception 'completed morphology ingestion payload/evidence is immutable'; end if; return NEW; end; $$ language plpgsql;
create trigger trg_morph_analysis_completed_immutable before update or delete on morphological_analysis for each row execute function block_completed_morphology_payload_update();
create trigger trg_alignment_completed_immutable before update or delete on annotation_alignment for each row execute function block_completed_morphology_payload_update();''')

def downgrade():
    op.execute('''drop trigger if exists trg_alignment_completed_immutable on annotation_alignment; drop trigger if exists trg_morph_analysis_completed_immutable on morphological_analysis; drop function if exists block_completed_morphology_payload_update(); drop trigger if exists trg_completed_morphology_run_immutable on morphology_ingestion_run; drop function if exists block_completed_morphology_run_update(); drop trigger if exists trg_alignment_config_frozen on alignment_configuration; drop trigger if exists trg_feature_profile_frozen on morphology_feature_mapping_profile; drop trigger if exists trg_transliteration_profile_frozen on transliteration_profile; drop trigger if exists trg_annotation_source_record_immutable on annotation_source_record; drop trigger if exists trg_annotation_source_release_immutable on annotation_source_release; drop function if exists block_phase3a_immutable();''')
    for t in ["morphology_export_manifest","annotation_alignment","morphological_segment","morphological_analysis","morphology_ingestion_run","alignment_configuration","morphology_feature_mapping_profile","transliteration_profile","annotation_source_record","annotation_source_release"]: op.drop_table(t)
