"""initial phase1 schema

Revision ID: 202607210001
Revises: 
Create Date: 2026-07-21 00:01:00
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "202607210001"
down_revision = None
branch_labels = None
depends_on = None

json_type = postgresql.JSONB(astext_type=sa.Text())

def upgrade():
    op.create_table("source_release", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("source_name", sa.String(200), nullable=False), sa.Column("source_version", sa.String(100), nullable=False), sa.Column("source_url", sa.Text()), sa.Column("source_format", sa.String(50), nullable=False), sa.Column("original_filename", sa.Text(), nullable=False), sa.Column("stored_filename", sa.Text(), nullable=False), sa.Column("encoding", sa.String(40), nullable=False), sa.Column("sha256", sa.String(64), nullable=False), sa.Column("byte_size", sa.Integer(), nullable=False), sa.Column("line_count", sa.Integer(), nullable=False), sa.Column("registered_at", sa.DateTime(), nullable=False), sa.Column("license", sa.Text()), sa.Column("metadata_json", json_type, nullable=False), sa.Column("notes", sa.Text()), sa.UniqueConstraint("source_name","source_version"), sa.UniqueConstraint("sha256"), sa.CheckConstraint("byte_size >= 0"), sa.CheckConstraint("line_count >= 0"))
    op.create_table("surah", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("source_release_id", sa.Integer(), sa.ForeignKey("source_release.id"), nullable=False), sa.Column("surah_number", sa.Integer(), nullable=False), sa.Column("source_order", sa.Integer(), nullable=False), sa.Column("arabic_name", sa.Text()), sa.Column("transliterated_name", sa.Text()), sa.Column("metadata_json", json_type, nullable=False), sa.UniqueConstraint("source_release_id","surah_number"), sa.UniqueConstraint("source_release_id","source_order"), sa.CheckConstraint("surah_number > 0"), sa.CheckConstraint("source_order > 0"))
    op.create_table("text_unit", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("source_release_id", sa.Integer(), sa.ForeignKey("source_release.id"), nullable=False), sa.Column("surah_id", sa.Integer(), sa.ForeignKey("surah.id"), nullable=False), sa.Column("unit_type", sa.String(40), nullable=False), sa.Column("surah_number", sa.Integer(), nullable=False), sa.Column("ayah_number", sa.Integer()), sa.Column("source_order", sa.Integer(), nullable=False), sa.Column("global_numbered_ayah_position", sa.Integer()), sa.Column("text_raw", sa.Text(), nullable=False), sa.Column("source_line_number", sa.Integer()), sa.Column("source_byte_start", sa.Integer()), sa.Column("source_byte_end", sa.Integer()), sa.Column("metadata_json", json_type, nullable=False), sa.UniqueConstraint("source_release_id","source_order"), sa.UniqueConstraint("source_release_id","global_numbered_ayah_position"), sa.CheckConstraint("source_order > 0"))
    op.create_table("source_line", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("source_release_id", sa.Integer(), sa.ForeignKey("source_release.id"), nullable=False), sa.Column("source_line_number", sa.Integer(), nullable=False), sa.Column("record_type", sa.String(40), nullable=False), sa.Column("raw_line_content", sa.Text(), nullable=False), sa.Column("line_ending", sa.String(4), nullable=False), sa.Column("byte_start", sa.Integer(), nullable=False), sa.Column("byte_end", sa.Integer(), nullable=False), sa.Column("classification_reason", sa.Text(), nullable=False), sa.Column("parsed_text_unit_id", sa.Integer(), sa.ForeignKey("text_unit.id")), sa.Column("metadata_json", json_type, nullable=False), sa.UniqueConstraint("source_release_id","source_line_number"), sa.CheckConstraint("record_type in ('ayah_record','blank','source_metadata','license','comment','unknown')"), sa.CheckConstraint("source_line_number > 0"), sa.CheckConstraint("byte_start >= 0"), sa.CheckConstraint("byte_end >= byte_start"))
    op.create_table("orthographic_token", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("text_unit_id", sa.Integer(), sa.ForeignKey("text_unit.id"), nullable=False), sa.Column("token_in_unit", sa.Integer(), nullable=False), sa.Column("token_in_surah", sa.Integer(), nullable=False), sa.Column("token_in_numbered_stream", sa.Integer()), sa.Column("token_in_full_source_stream", sa.Integer(), nullable=False), sa.Column("surface_raw", sa.Text(), nullable=False), sa.Column("delimiter_before", sa.Text(), nullable=False), sa.Column("delimiter_after", sa.Text(), nullable=False), sa.Column("start_codepoint_in_unit", sa.Integer(), nullable=False), sa.Column("end_codepoint_in_unit", sa.Integer(), nullable=False), sa.Column("start_byte_in_unit", sa.Integer()), sa.Column("end_byte_in_unit", sa.Integer()), sa.Column("tokenizer_version", sa.String(40), nullable=False), sa.UniqueConstraint("text_unit_id","token_in_unit"))
    op.create_table("unicode_codepoint", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("text_unit_id", sa.Integer(), sa.ForeignKey("text_unit.id"), nullable=False), sa.Column("orthographic_token_id", sa.Integer(), sa.ForeignKey("orthographic_token.id")), sa.Column("codepoint_in_text_unit", sa.Integer(), nullable=False), sa.Column("codepoint_in_token", sa.Integer()), sa.Column("codepoint_in_numbered_stream", sa.Integer()), sa.Column("codepoint_in_full_source_stream", sa.Integer(), nullable=False), sa.Column("character", sa.Text(), nullable=False), sa.Column("unicode_hex", sa.String(12), nullable=False), sa.Column("unicode_name", sa.Text(), nullable=False), sa.Column("general_category", sa.String(4), nullable=False), sa.Column("canonical_combining_class", sa.Integer(), nullable=False), sa.Column("is_combining_mark", sa.Boolean(), nullable=False), sa.Column("is_whitespace", sa.Boolean(), nullable=False), sa.Column("is_punctuation", sa.Boolean(), nullable=False), sa.Column("is_quranic_annotation", sa.Boolean(), nullable=False), sa.Column("metadata_json", json_type, nullable=False), sa.UniqueConstraint("text_unit_id","codepoint_in_text_unit"))
    op.create_table("analytical_character", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("unicode_codepoint_id", sa.Integer(), sa.ForeignKey("unicode_codepoint.id"), nullable=False), sa.Column("source_release_id", sa.Integer(), sa.ForeignKey("source_release.id"), nullable=False), sa.Column("text_unit_id", sa.Integer(), sa.ForeignKey("text_unit.id"), nullable=False), sa.Column("address_space", sa.String(80), nullable=False), sa.Column("position_in_address_space", sa.Integer(), nullable=False), sa.Column("character", sa.Text(), nullable=False), sa.Column("metadata_json", json_type, nullable=False), sa.UniqueConstraint("source_release_id","address_space","position_in_address_space"))
    op.create_table("grapheme_cluster", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("text_unit_id", sa.Integer(), sa.ForeignKey("text_unit.id"), nullable=False), sa.Column("orthographic_token_id", sa.Integer(), sa.ForeignKey("orthographic_token.id")), sa.Column("grapheme_in_text_unit", sa.Integer(), nullable=False), sa.Column("grapheme_in_token", sa.Integer()), sa.Column("raw_value", sa.Text(), nullable=False), sa.Column("start_codepoint_in_text_unit", sa.Integer(), nullable=False), sa.Column("end_codepoint_in_text_unit", sa.Integer(), nullable=False), sa.Column("segmentation_version", sa.String(40), nullable=False), sa.UniqueConstraint("text_unit_id","grapheme_in_text_unit"))
    op.create_table("normalization_profile", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(120), nullable=False), sa.Column("version", sa.String(40), nullable=False), sa.Column("description", sa.Text(), nullable=False), sa.Column("configuration_json", json_type, nullable=False), sa.Column("configuration_sha256", sa.String(64), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("is_frozen", sa.Boolean(), nullable=False), sa.UniqueConstraint("name","version"))
    op.create_table("normalized_token", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("orthographic_token_id", sa.Integer(), sa.ForeignKey("orthographic_token.id"), nullable=False), sa.Column("normalization_profile_id", sa.Integer(), sa.ForeignKey("normalization_profile.id"), nullable=False), sa.Column("normalized_value", sa.Text(), nullable=False), sa.Column("transformation_log_json", json_type, nullable=False), sa.UniqueConstraint("orthographic_token_id","normalization_profile_id"))
    op.create_table("query_scope_definition", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(120), nullable=False), sa.Column("version", sa.String(40), nullable=False), sa.Column("description", sa.Text(), nullable=False), sa.Column("configuration_json", json_type, nullable=False), sa.Column("configuration_sha256", sa.String(64), nullable=False), sa.Column("is_frozen", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.UniqueConstraint("name","version"))
    op.create_table("analysis_run", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("analysis_type", sa.String(80), nullable=False), sa.Column("source_release_id", sa.Integer(), sa.ForeignKey("source_release.id"), nullable=False), sa.Column("scope_configuration_json", json_type, nullable=False), sa.Column("normalization_profile_id", sa.Integer(), sa.ForeignKey("normalization_profile.id")), sa.Column("tokenizer_version", sa.String(40), nullable=False), sa.Column("software_version", sa.String(40), nullable=False), sa.Column("query_parameters_json", json_type, nullable=False), sa.Column("query_hash", sa.String(64), nullable=False), sa.Column("started_at", sa.DateTime(), nullable=False), sa.Column("completed_at", sa.DateTime()), sa.Column("status", sa.String(40), nullable=False), sa.Column("result_count", sa.Integer()), sa.Column("result_manifest_path", sa.Text()), sa.Column("error_message", sa.Text()))
    op.create_table("analysis_evidence", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("analysis_run_id", sa.Integer(), sa.ForeignKey("analysis_run.id"), nullable=False), sa.Column("result_index", sa.Integer(), nullable=False), sa.Column("text_unit_id", sa.Integer(), sa.ForeignKey("text_unit.id"), nullable=False), sa.Column("orthographic_token_id", sa.Integer(), sa.ForeignKey("orthographic_token.id")), sa.Column("codepoint_start", sa.Integer()), sa.Column("codepoint_end", sa.Integer()), sa.Column("raw_value", sa.Text(), nullable=False), sa.Column("normalized_value", sa.Text()), sa.Column("inclusion_reason", sa.Text(), nullable=False), sa.Column("evidence_json", json_type, nullable=False))

def downgrade():
    for table in ("analysis_evidence","analysis_run","query_scope_definition","normalized_token","normalization_profile","grapheme_cluster","analytical_character","unicode_codepoint","orthographic_token","source_line","text_unit","surah","source_release"):
        op.drop_table(table)
